### ISSUE TITLE
Návrh

### ISSUE THREAD

**Issue by Creeperface01** [GamakCZ/MyHelp#3]
nehci nic říkat ale existuje i "if" ne jenom switch :D takže místo switche s jednou možností můžeš použít if :D

**Comment by GamakCZ** [comment]
tak sem ti to upravil...

**Comment by Creeperface01** [comment]
Mě to je jedno :D jen se ti snažím pomoct

**Comment by Creeperface01** [comment]
Udělal jsi to stejně blbě tak to radši nech tak jak to bylo :D

**Comment by GamakCZ** [comment]
Už to chápu :D
